const data = {
  //************* */
  // Menu item data
  //************* */
  menuItems: [
    {
      dataCategory: "shawarma",
      img: "../images/thumbnails/shawarmaThumbnail.jpg",
      alt: "Shawarma",
      name: "Shawarma",
      desc: "Explore our full shawarma collection with every flavour-packed option.",
      link: "Html/shawarma.html",
    },
    {
      dataCategory: "fried-chicken",
      img: "../images/thumbnails/friedChickenThumbnail.png",
      alt: "Fried Chicken",
      name: "Fried Chicken",
      desc: "Crispy herb falafel, hummus, roasted peppers, cucumber, and lemon tahini wrapped fresh.",
      link: "Html/friedChicken.html",
    },
    {
      dataCategory: "burger",
      img: "../images/thumbnails/burgerThumbnail.png",
      alt: "Burger (Fried Chicken)",
      name: "Burger (Fried Chicken)",
      desc: "Crispy herb falafel, hummus, roasted peppers, cucumber, and lemon tahini wrapped fresh.",
      link: "Html/burger.html",
    },
    {
      dataCategory: "alfaham",
      img: "../images/thumbnails/alfahamthumbnail.png",
      alt: "Alfaham",
      name: "Alfaham",
      desc: "Experience the taste of our signature Alfaham with a perfect blend of flavors.",
      link: "Html/alfaham.html",
    },
    {
      dataCategory: "grill-chicken",
      img: "../images/thumbnails/grilledChickenThumbnail.png",
      alt: "Grill Chicken",
      name: "Grill Chicken",
      desc: "Juicy grilled chicken, seasoned to perfection with a blend of herbs and spices.",
      link: "Html/grillChicken.html",
    },
    {
      dataCategory: "chicken-kebab",
      img: "../images/thumbnails/chickenKebabThumbnail.png",
      alt: "Chicken Kebab",
      name: "Chicken Kebab",
      desc: "Tender chicken kebabs, marinated in a blend of aromatic spices and grilled to perfection.",
      link: "Html/chickenKebab.html",
    },
    {
      dataCategory: "starters",
      img: "../images/thumbnails/startersThumbnail.png",
      alt: "Starters",
      name: "Starters",
      desc: "Delicious starters to kick off your meal with a burst of flavor.",
      link: "Html/starters.html",
    },
    {
      dataCategory: "chicken-wrap",
      img: "../images/thumbnails/chickenWrapThumbnail.png",
      alt: "Chicken Wrap",
      name: "Chicken Wrap",
      desc: "A delicious wrap filled with tender chicken, fresh vegetables, and our signature sauce.",
      link: "Html/chickenWrap.html",
    },
    {
      dataCategory: "mojito",
      img: "../images/thumbnails/mojitoThumbnail.png",
      alt: "Mojito",
      name: "Mojito",
      desc: "A refreshing blend of mint, lime, and rum, perfect for a cool drink.",
      link: "Html/mojito.html",
    },
    {
      dataCategory: "shakes",
      img: "../images/thumbnails/shakesThumbnail.png",
      alt: "Shakes",
      name: "Shakes",
      desc: "Indulge in our creamy shakes, made with real ingredients for a delicious treat.",
      link: "Html/shakes.html",
    },
    {
      dataCategory: "juices",
      img: "../images/thumbnails/juicesThumbnail.png",
      alt: "Juices",
      name: "Juices",
      desc: "Freshly squeezed juices bursting with natural flavors and nutrients.",
      link: "Html/juices.html",
    },
    {
      dataCategory: "desserts",
      img: "../images/thumbnails/dessertsThumbnail.png",
      alt: "Desserts",
      name: "Desserts",
      desc: "Satisfy your sweet tooth with our delectable desserts, crafted to perfection.",
      link: "Html/desserts.html",
    },
  ],

  //***************** */
  // Shawarma item data
  //***************** */
  shawarmaItems: [
    {
      dataCategory: "classic-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Classic Shawarma",
      name: "Classic Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "limbo-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Limbo Shawarma",
      name: "Limbo Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "elite-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Elite Shawarma",
      name: "Elite Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "peri-peri-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Peri-Peri Shawarma",
      name: "Peri-Peri Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "mexican-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Mexican Shawarma",
      name: "Mexican Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "hot-&-pepper-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Hot & Pepper Shawarma",
      name: "Hot & Pepper Shawarma",
      desc: "Experience the taste of our signature Hot & Pepper Shawarma with a perfect blend of flavors.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "schezwan-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Schezwan Shawarma",
      name: "Schezwan Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "tandoori-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Tandoori Shawarma",
      name: "Tandoori Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "fire-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Fire Shawarma",
      name: "Fire Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "cottage-cheese-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Cottage Cheese Shawarma",
      name: "Cottage Cheese Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "jambo-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Jambo Shawarma",
      name: "Jambo Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "power-bite-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Power Bite Shawarma",
      name: "Power Bite Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "kebab-roll",
      img: "../images/shawarma/loading.jpg",
      alt: "Kebab Roll",
      name: "Kebab Roll",
      desc: "A delicious roll filled with seasoned kebabs, fresh vegetables, and our signature sauce.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "pot-shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Pot Shawarma",
      name: "Pot Shawarma",
      desc: "A hearty serving of our signature pot shawarma, packed with tender meat and aromatic spices.",
      price: { roll: "₹60", palte: "₹110" },
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // Bunshawarma item data
  //************* */
  bunShawarmaItems: [
    {
      dataCategory: "classic-Bun-Shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Classic Bun Shawarma",
      name: "Classic Bun Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹45",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "flavor-Bun-Shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Flavor Bun Shawarma",
      name: "Flavor Bun Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹55",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // Cone shawarma item data
  //************* */
  coneShawarmaItems: [
    {
      dataCategory: "classic-Cone-Shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Classic Cone Shawarma",
      name: "Classic Cone Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹25",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "flavor-Cone-Shawarma",
      img: "../images/shawarma/loading.jpg",
      alt: "Flavor Cone Shawarma",
      name: "Flavor Cone Shawarma",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹35",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // Fried Chicken item data
  //************* */
  friedChickenItems: [
    {
      dataCategory: "chicken-pops",
      img: "../images/friedChicken/loading.jpg",
      alt: "Chicken Pops",
      name: "Chicken Pops",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "bone-shots",
      img: "../images/friedChicken/loading.jpg",
      alt: "Bone Shots",
      name: "Bone Shots",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹80",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "chicken-wings",
      img: "../images/friedChicken/loading.jpg",
      alt: "Chicken Wings",
      name: "Chicken Wings<br>(4 pcs)",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹80",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "chicken-lollipops",
      img: "../images/friedChicken/loading.jpg",
      alt: "Chicken Lollipops",
      name: "Chicken Lollipops<br>(4 pcs)",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹110",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "chicken-strips",
      img: "../images/friedChicken/loading.jpg",
      alt: "Chicken Strips",
      name: "Chicken Strips<br>(4 pcs)",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹120",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "loaded-fries",
      img: "../images/friedChicken/loading.jpg",
      alt: "Loaded Fries",
      name: "Loaded Fries",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹130",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "Drumsticks",
      img: "../images/friedChicken/loading.jpg",
      alt: "Drumsticks",
      name: "Drumsticks<br>(2 pcs)",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹130",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "infused-fried-chicken",
      img: "../images/friedChicken/loading.jpg",
      alt: "Infused Fried Chicken",
      name: "Infused Fried Chicken",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹150",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // burger item data
  //************* */
  burgerItems: [
    {
      dataCategory: "chicken-burger",
      img: "../images/burger/loading.jpg",
      alt: "Chicken Burger",
      name: "Chicken Burger",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "cheese-chicken-burger",
      img: "../images/burger/loading.jpg",
      alt: "Cheese Chicken Burger",
      name: "Cheese Chicken Burger",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "zinger-burger",
      img: "../images/burger/loading.jpg",
      alt: "Zinger Burger",
      name: "Zinger Burger",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "periperi-burger",
      img: "../images/burger/loading.jpg",
      alt: "Peri Peri Burger",
      name: "Peri Peri Burger",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "no-bun-burger",
      img: "../images/burger/loading.jpg",
      alt: "No Bun Burger",
      name: "No Bun Burger",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹150",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // Alfaham item data
  //************* */
  alfahamItems: [
    {
      dataCategory: "chicken-Alfaham",
      img: "../images/Alfaham/loading.jpg",
      alt: "Chicken Alfaham",
      name: "Chicken Alfaham",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { Qrt: "₹130", Half: "₹210", Full: "₹400" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "Tandoori-Alfaham",
      img: "../images/Alfaham/loading.jpg",
      alt: "Tandoori Alfaham",
      name: "Tandoori Alfaham",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { Qrt: "₹130", Half: "₹210", Full: "₹400" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "hariyali-Alfaham",
      img: "../images/Alfaham/loading.jpg",
      alt: "Hariyali Alfaham",
      name: "Hariyali Alfaham",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { Qrt: "₹160", Half: "₹240", Full: "₹450" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "periperi-Alfaham",
      img: "../images/Alfaham/loading.jpg",
      alt: "Peri Peri Alfaham",
      name: "Peri Peri Alfaham",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { Qrt: "₹160", Half: "₹240", Full: "₹450" },
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // Grill Chicken item data
  //************* */
  grillChickenItems: [
    {
      dataCategory: "Grilled-Chicken",
      img: "../images/grilledChicken/loading.jpg",
      alt: "Grilled Chicken",
      name: "Grilled Chicken",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { Qrt: "₹140", Half: "₹190", Full: "₹390" },
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "saucy-Grilled-Chicken",
      img: "../images/grilledChicken/loading.jpg",
      alt: "Saucy Grilled Chicken",
      name: "Saucy Grilled Chicken",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: { Qrt: "--", Half: "₹250", Full: "₹450" },
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // Kebab item data
  //************* */
  kebabItems: [
    {
      dataCategory: "chicken-kebab",
      img: "../images/kebab/loading.jpg",
      alt: "Chicken Kebab",
      name: "Chicken Kebab",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹100",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "hariyali-kebab",
      img: "../images/kebab/loading.jpg",
      alt: "Hariyali Kebab",
      name: "Hariyali Kebab",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹120",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "limbo-kebab",
      img: "../images/kebab/loading.jpg",
      alt: "Limbo Kebab",
      name: "Limbo Kebab",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹120",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "periperi-kebab",
      img: "../images/kebab/loading.jpg",
      alt: "Peri Peri Kebab",
      name: "Peri Peri Kebab",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹130",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // starters item data
  //************* */
  startersItems: [
    {
      dataCategory: "french-fries",
      img: "../images/starters/loading.jpg",
      alt: "French Fries",
      name: "French Fries",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹50",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "nuggets",
      img: "../images/starters/loading.jpg",
      alt: "Chicken Nuggets",
      name: "Chicken Nuggets",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹50",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "peri-peri-fries",
      img: "../images/starters/loading.jpg",
      alt: "Peri Peri Fries",
      name: "Peri Peri Fries",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "Masala-fries",
      img: "../images/starters/loading.jpg",
      alt: "Masala Fries",
      name: "Masala Fries",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹65",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "crab-lollipops",
      img: "../images/starters/loading.jpg",
      alt: "Crab Lollipops",
      name: "Crab Lollipops",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // chicken wrap item data
  //************* */
  chickenWrapItems: [
    {
      dataCategory: "classic-wrap",
      img: "../images/wrap/loading.jpg",
      alt: "Classic Wrap",
      name: "Classic Wrap",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹80",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "periperi-wrap",
      img: "../images/wrap/loading.jpg",
      alt: "Peri Peri Wrap",
      name: "Peri Peri Wrap",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "BBQ-wrap",
      img: "../images/wrap/loading.jpg",
      alt: "BBQ Wrap",
      name: "BBQ Wrap",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "schezwan-wrap",
      img: "../images/wrap/loading.jpg",
      alt: "Schezwan Wrap",
      name: "Schezwan Wrap",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "cheesy-wrap",
      img: "../images/wrap/loading.jpg",
      alt: "Cheesy Wrap",
      name: "Cheesy Wrap",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹100",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // mojito item data
  //************* */
  mojitoItems: [
    {
      dataCategory: "blue-curacao-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Blue Curacao Mojito",
      name: "Blue Curacao Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "mint-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Mint Mojito",
      name: "Mint Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "orange-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Orange Mojito",
      name: "Orange Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "green-apple-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Green Apple Mojito",
      name: "Green Apple Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "lychee-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Lychee Mojito",
      name: "Lychee Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "rose-berry-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Rose Berry Mojito",
      name: "Rose Berry Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹80",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "passion-fruit-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Passion Fruit Mojito",
      name: "Passion Fruit Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹80",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // shakes item data
  //************* */
  shakesItems: [
    {
      dataCategory: "oreo-shake",
      img: "../images/shakes/loading.jpg",
      alt: "Oreo Shake",
      name: "Oreo Shake",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "Kit-Kat-Shake",
      img: "../images/shakes/loading.jpg",
      alt: "Kit-Kat Shake",
      name: "Kit-Kat Shake",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "cold-coffee",
      img: "../images/shakes/loading.jpg",
      alt: "Cold Coffee",
      name: "Cold Coffee",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "cold-boost",
      img: "../images/shakes/loading.jpg",
      alt: "Cold Boost",
      name: "Cold Boost",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "lychee-mojito",
      img: "../images/mojito/loading.jpg",
      alt: "Lychee Mojito",
      name: "Lychee Mojito",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹70",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "blueberry-shake",
      img: "../images/shakes/loading.jpg",
      alt: "Blueberry Shake",
      name: "Blueberry Shake",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹80",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "blackcurrent-shake",
      img: "../images/shakes/loading.jpg",
      alt: "Blackcurrent Shake",
      name: "Blackcurrent Shake",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹80",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "sharjha-shake",
      img: "../images/shakes/loading.jpg",
      alt: "Sharjha Shake",
      name: "Sharjha Shake",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "brownie-shake",
      img: "../images/shakes/loading.jpg",
      alt: "Brownie Shake",
      name: "Brownie Shake",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹110",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // juices item data
  //************* */
  juicesItems: [
    {
      dataCategory: "lime-juice",
      img: "../images/juices/loading.jpg",
      alt: "Lime Juice",
      name: "Lime Juice",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹40",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "italian-grape-juice",
      img: "../images/juices/loading.jpg",
      alt: "Italian Grape Juice",
      name: "Italian Grape Juice",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹50",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "nongu-pal",
      img: "../images/juices/loading.jpg",
      alt: "Nongu Pal",
      name: "Nongu Pal",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "jigarthanda",
      img: "../images/juices/loading.jpg",
      alt: "Jigarthanda",
      name: "Jigarthanda",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
  ],

  //************* */
  // Desserts item data
  //************* */
  dessertsItems: [
    {
      dataCategory: "fruit-custard",
      img: "../images/desserts/loading.jpg",
      alt: "Fruit Custard",
      name: "Fruit Custard",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹50",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "elaneer-pudding",
      img: "../images/desserts/loading.jpg",
      alt: "Elaneer Pudding",
      name: "Elaneer Pudding",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹50",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "kerala-payasam",
      img: "../images/desserts/loading.jpg",
      alt: "Kerala Payasam",
      name: "Kerala Payasam",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹60",
      bestseller: true,
      special: true,
    },
    {
      dataCategory: "Brownie+Ice-Cream",
      img: "../images/desserts/loading.jpg",
      alt: "Brownie + Ice Cream",
      name: "Brownie + Ice Cream",
      desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      price: "₹90",
      bestseller: true,
      special: true,
    },
  ],
};

